navarasu/onedark.nvim

lua/onedark/highlights.lua

Add LspReferenceText, LspReferenceWrite and LspReferenceRead highlight
groups. These are required to use the function
`vim.lsp.buf.document_highlight()`.
I’m not sure only underlining is the best option, as it is associated with errors as well.
I’ve considered using `{fg = c.bg0, bg = c.orange},` as with `IncSearch`, but it is quite intrusive. You have put together this great colorscheme, so I’m sure you’ll pick something good for this highlight group!

Add support for LspReference*

---

README.md
lua/onedark/highlights.lua

Hop.nvim is a bit like EasyMotion, but written in lua.
I realize it may not be desirable to add every possible plugin. Hop.nvim seems to require very few highlight group definition though, so it may be worth having by default.
This is what an “active jump” looks like:

Add hop.nvim plugin support

---

README.md
lua/onedark/config.lua
lua/onedark/terminal.lua

The colorscheme is not playing very nice with my terminal scheme, so I'd prefer to have it disabled on neovim.
This puts the terminal colors change behind a flag so users can disable if they want.
Hope this pr is in a good shape for this repo.

feat: allow disable terminal colors

---

lua/onedark/highlights.lua

- fix indentation in `highlights.lua`
- Support vimtex and better treesitter highlighting for latex
- Bold statement for all languages was a bad idea, reverting back and making it bold only for some languages (c, cpp, and vimscript at the moment)
- I think purple for icon kind in nvim-cmp looks better, thoughts?

Improve latex highlights + minor fixes

---

lua/onedark/highlights.lua

The current theme does not have groups for float windows, and makes the borders of float windows hard to distinguish since it defaults to some highlight group whose foreground color is dark gray.
This PR fixes this problem by adding two specific groups for float windows, namely `NormalFloat` and `FloatBorder`, and uses proper color from the palette.

Add highlight group for float windows

---

README.md
lua/onedark/highlights.lua
lua/onedark/init.lua

- Improve some highlights
- Add support for barbar plugin
- Add support for aerial plugin
- Add `cmp_itemkind_reverse` option, to reverse item kind color in cmp menu

Add option to reverse cmp kind highlights and add support for Aerial

---

lua/onedark/highlights.lua

- LspCodeLens has the same style as Comment
- LspCodeLensSeparator only has the Comment's fg

Add LSP Code Lens highlights

---

lua/onedark/palette.lua

This PR fixes issue #61.
The colors for added and deleted regions are taken from Atom using an eyedropper tool.
Since Atom doesn't have a color for changed regions, I've used a tetrad color of the color for added regions.
Here is a screenshot:

Fix diff coloring in light mode

---

README.md
lua/onedark/highlights.lua

Hi! I would like to add explicit support for [mini.nvim](https://github.com/echasnovski/mini.nvim).
Basic choices are taken from highlight groups to which 'mini.nvim' makes links by default or from analogous plugins.
Differences from default linked groups:
- 'mini.jump2d' is based on 'Hop'. Added `nocombine` for it to always be consistent (not become italic on italic text).
- 'mini.starter' is based on 'dashboard.lua' and personal choices:
- `MiniStarterItemBullet` is as border.
- `MiniStarterItemPrefix` and `MiniStarterQuery` are based on "warning" and "info" diagnostic colors to be opposite of each other.
- 'mini.statusline' is based on 'lualine/themes/onedark.lua' and personal choices:
- `MiniStatuslineDevinfo` and `MiniStatuslineFileinfo` have slightly different background.
- …

Add explicit support for 'mini.nvim'

---

lua/lualine/themes/onedark.lua

Hi,
I'm using a terminal emulator with transparent background, so I've also configured my nvim (and onedark theme) to be transparent.
I noticed that despite I'm setting `transparent = true`, my lualine background is not transparent. So, I added a check for this setting in the lualine theme.
What do you think about this? Should it be a separate setting?

support transparent lualine background

---

README.md
lua/onedark/init.lua

Fix #89 
As @itaranto said, it should be disabled by default. See https://github.com/navarasu/onedark.nvim/issues/89#issuecomment-1195730099
Also deprecate #91, because now `toggle_style_key` is disabled with `nil` value and not empty string

Disable `toggle_style_key` by default

---

README.md
lua/lualine/themes/onedark.lua
lua/onedark/init.lua

Added transparency customization for Lualine separate from global transparency option. This new 'lualine' config table might be extended for future lualine-specific customizations.
I just wanted my lualine to not be transparent when I set the plugin transparency to true :)

Specific lualine transparency

---

README.md

As we know after neovim 0.8 TreeSitter keywords have been changed and this pull request updates README file accordingly

customization example updated in readme

---

lua/onedark/highlights.lua

Add highlight groups for [nvim-navic](https://github.com/SmiteshP/nvim-navic) to get a colored winbar.

Add support for nvim-navic

---

lua/onedark/highlights.lua

Add highlights support for indent-blankline.nvim plugin

---

lua/onedark/highlights.lua

* Fix indentBlankline hl group names
* Add plugin missing hl groups
* Use grey for MiniIndentscopeSymbol
Fixes: 8a082b9153d1 ("fix(plugin): indentBlankline hl group names")

fix(plugin): indentBlankline hl group names

---

lua/onedark/highlights.lua

This gives CurSearch a bg color different from the regular Search yellow. This makes it much easier to tell where the cursor is when there are multiple matches.

Add CurSearch highlight color to help distinguish current position

---

lua/onedark/highlights.lua

Fixes #104 
Fixes #127 
Although it is possible for user to change the color for `rainbowcol1` as mentioned in #127, I still believe that this is an better default as it:
- does not look significantly worse.
- does not get covered up by MatchParen's background.

changed rainbowcol1 to lightgrey

---

lua/onedark/highlights.lua

Fixes #156.
Fixes #140.
I wouldn't say I've made semantic tokens look good on every languages out there, but I do think this is good enough to be merged for now and be slowly improved later on. I do also think it is a significant improvement over how semantic tokens currently looks with nvim 0.9.
Here's how rust looks with treesitter only highlighting:
Here's how the same piece of rust looks with semantic token but before this PR, as you can see, it's quite unsightly:
Here's how the same piece of rust looks with semantic token after this PR, notice how the doc test got syntax highlighting as it has been labeled by rust-analyzer:
BTW, I don't think parameters should be red but I can't think of any better color other than white so I'm opened to suggestions.

Adding semantic token support

---

lua/onedark/highlights.lua

This PR adds highlight groups of nvim-ts-rainbow2 since it is the active fork of nvim-ts-rainbow.
I didn't remove the old highlight groups since some people might be still using it and it doesn't bother anyone.

Add nvim-ts-rainbow2 support

---

lua/onedark/highlights.lua

Constants in Rust (and probably other languages) started just being white with semantic highlighting enabled. With this PR, they are highlighted as constants, as they are without semantic highlighting.

`@lsp.typemod.variable.static` set to `@constant`

---

lua/onedark/highlights.lua

This PR adds an explicit style for tree-sitter's `@preproc`, although Neovim already automatically uses the style defined for `Preproc`. I just think it's cleaner to directly specify it.

add explicit style for `@preproc`

---

lua/onedark/highlights.lua

This commit properly highlights indent blankline plugin highlights using the correct internal api using `fmt` instead of `gui`. This commit also removes an unused highlight. Currently the current context is not highlighted or underlined at all due to the bug in the format of the lua table. This fixes that issue. Thanks

fix: correctly highlight indent blankline context using fmt

---

lua/onedark/highlights.lua

Add support for [HiPhish/rainbow-delimiters.nvim](https://github.com/HiPhish/rainbow-delimiters.nvim) which is the successor to the now-deprecated [HiPhish/nvim-ts-rainbow2](https://github.com/HiPhish/nvim-ts-rainbow2)

Add support for rainbow-delimiters.nvim

---

lua/onedark/highlights.lua

<table role="table">
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
Due to the fact that treesitter added new global highlighter it does effects the highliting of decorators.
Ref: https://github.com/nvim-treesitter/nvim-treesitter/pull/5113

Handle typescript incorrect highlights

---

README.md
lua/onedark/highlights.lua

IndentBlankline v3 now uses different highlight groups. Add the new groups to reflect that.
See: https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Migrate-to-version-3
Also add IndentBlankline to readme as supported plugin

fix(ibl): add updated IndentBlankline highlights

---

lua/onedark/highlights.lua

PR #190 was supposed to add support for IBL v3, but actually caused a visual change, because it explictly defined the groups, which caused the IBL fallbacks to be not used, but at the same time didn't specify `fg`, which is what's used by IBL v3.
Preview for this PR (notice the underline color):
Before:
After:

Actually fix IndentBlankline v3 highlights.

---

lua/onedark/highlights.lua

`VertSplit` highlight group was [deprecated and replaced](https://github.com/neovim/neovim/pull/17266) with `WinSeparator` in Neovim 0.7.0. The default colorscheme linked `WinSeparator` to `VertSplit` and Onedark inherited this behavior, so it was okay to only define `VertSplit`. However, a [change of default colorscheme](https://github.com/neovim/neovim/pull/26334) was recently merged in Neovim and broke "legacy" colorschemes in [various ways](https://github.com/neovim/neovim/issues/26378) (see item 3 specifically). As a result, the window separator looks as follows in Onedark on the latest Neovim nightly:
This PR fixes that:

Replace deprecated VertSplit with WinSeparator

---

lua/onedark/highlights.lua

After the PR #203 I though it is a good idea to keep old capture names for people who doesn't updated treesitter.
This PR set back the old capture names in highlight config

Keep old TS capture names for retrocompatibility

---

lua/onedark/highlights.lua

This pr simply defines the treesitter highlight groups `@markup.heading.*.markdown` and `@markup.heading.*.marker.markdown` to make different levels of markdown headings distinguishable when treesitter is enabled on markdown files.
~~I have also **moved** the treesitter related highlight settings **down** so that I can reference highlight settings in `hl.lang.markdown` to avoid redundant definitions.~~

Make markdown headings distinguishable with treesitter

---

lua/onedark/highlights.lua

Add explicit support for all new groups since #87 and for the (hopefully) upcoming 'mini.icons'.

Add new 'mini.nvim' highlight groups

---

lua/onedark/highlights.lua

Fix NvimTree Floating Windows. The background colour is completely broken otherwise. Please see: https://github.com/nvim-tree/nvim-tree.lua/blob/master/doc/nvim-tree-lua.txt section 8.1.
Thanks for the theme!

Fix NvimTree Floating Windows
